parameters:
    adherent_interests:
        agriculture: Agriculture
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Egalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        institution: Institution
        jeunesse: Jeunesse
        justice: Justice
        logement: Logement
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        territoire: Territoire
